### ISSUE TITLE
Weird end-effector draggable points location

### ISSUE THREAD

**Issue by tgaudin** [dilevin/computer-graphics-kinematics#18]
It seems that the end-effector poins are weirdly located... I can not figure out why.

Is my ikea lamp broken? Did Bob get sick of playing puppet? ¯\_(ツ)_/¯ 

Any (better) hint?

<img width="417" alt="Screen Shot 2020-03-06 at 03 01 29" src="https://user-images.githubusercontent.com/14755997/76043187-0b9f3c80-5f57-11ea-9082-4af03b510f4c.png">
<img width="604" alt="Screen Shot 2020-03-06 at 03 02 10" src="https://user-images.githubusercontent.com/14755997/76043192-0d690000-5f57-11ea-8a69-9e968e677753.png">

**Comment by andriyDev** [comment]
This means your transformed tips is not working correctly. At least that was the case for me. In my case it was the fact that the vector I was multiplying by to get the tip point was in world space when it should have been in bone space (so that the transform would automatically put it at the tip of the bone).
